# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Prateek Srivastava
tagline:          Computer Engineer
description:
url:              prateek22sri.me
baseurl:          /

author:
  name:           'Prateek Srivastava'

#gems: [jekyll-paginate]
#paginate:         5
#paginate_path: "page:num"

# Custom vars
facebook: https://www.facebook.com/prateek22
github: https://github.com/prateek22sri
linkedin: https://www.linkedin.com/in/prateek22sri
